# https://docs.openshift.com/container-platform/4.11/rest_api/workloads_apis/cronjob-batch-v1.html
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      template:
        spec:
          containers:
          - name: run-validation
            image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-github
                  key: token
            - name: SENTRY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-sentry
                  key: dsn
            - name: DEPLOYMENT
              value: {{ .Values.deployment }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: OnFailure
