# https://docs.openshift.com/container-platform/4.11/rest_api/workloads_apis/cronjob-batch-v1.html
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      template:
        spec:
          containers:
          - name: {{ .Values.container.name }}
            image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_variables.github_token.name }}
                  key: {{ .Values.env_variables.github_token.key }}
            - name: SENTRY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_variables.sentry_dsn.name }}
                  key: {{ .Values.env_variables.sentry_dsn.key }}
            - name: DEPLOYMENT
              value: {{ .Values.env_variables.deployment.value }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: OnFailure
