# https://docs.openshift.com/container-platform/latest/rest_api/workloads_apis/cronjob-batch-v1.html
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: import-images
              image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
              env:
                - name: KUBECONFIG
                  value: /tmp/.kube/config
                - name: HOST
                  value: {{ .Values.host }}
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secret.name }}
                      key: {{ .Values.secret.key }}
                - name: SERVICE
                  value: {{ .Values.service }}
                - name: DEPLOYMENT
                  value: {{ .Values.deployment }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure
