apiVersion  : v2
name        : packit-service-validation
description : Helm chart for deploying packit-service-validation app
type        : application
# Increment each time you make changes to the chart and its templates.
version     : 1.3.0

keywords:
  - python
  - unified
  - deployment

maintainers:
  - name: The Packit team
    url: https://packit.dev
