deployment: ~

# Cron job parameters
cronjobs:
  - id: "daily-validation"
    # runs every day at 4 a.m.
    schedule: "0 4 * * *"
    # maximum duration is 4 hours
    activeDeadlineSeconds: 14400
  - id: "weekly-validation"
    # runs on wednesday at 4 a.m.
    schedule: "0 4 * * wed"
    # maximum duration is 4 hours
    activeDeadlineSeconds: 14400

# Container image
image:
  # Image repository without a tag
  repo: quay.io/packit/packit-service-validation
  # Image tag
  tag: ~

# Pod resources maximum
resources:
  limits:
    cpu: "100m"
    memory: "80Mi"
  requests:
    cpu: "100m"
    memory: "80Mi"

# Secrets
secrets:
  sentry: ~
  github: ~
  gitlab: ~
  gitlabgnome: ~
  gitlabfreedesktop: ~
  salsadebian: ~
