# https://docs.openshift.com/container-platform/latest/rest_api/workloads_apis/cronjob-batch-v1.html
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      template:
        spec:
          containers:
          - name: run-validation
            image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-github
                  key: token
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-gitlab
                  key: token
            - name: GITLAB_GNOME_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-gitlab-gnome
                  key: token
            - name: GITLAB_FREEDESKTOP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-gitlab-freedesktop
                  key: token
            - name: SALSA_DEBIAN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-salsa-debian
                  key: token
            - name: SENTRY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-sentry
                  key: dsn
            - name: DEPLOYMENT
              value: {{ .Values.deployment }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: OnFailure
