name: Deploy import-images cron job

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'helm-charts/import-images/**/*.yaml'
      - 'values/import-images/*.yaml'

jobs:
  deploy:
    # To not run in forks
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest
    environment: prod
    env:
      OC_SERVER: https://api.auto-prod.gi0n.p1.openshiftapps.com:6443
    strategy:
      matrix:
        project: [packit-prod, stream-prod, fedora-source-git-prod]

    steps:
      - uses: actions/checkout@v3

      - if: ${{ matrix.project == 'packit-prod' }}
        run: echo "secret_name_token=PACKIT_PROD_TOKEN" >> $GITHUB_ENV
      - if: ${{ matrix.project == 'stream-prod' }}
        run: echo "secret_name_token=STREAM_PROD_TOKEN" >> $GITHUB_ENV
      - if: ${{ matrix.project == 'fedora-source-git-prod' }}
        run: echo "secret_name_token=FEDORA_SOURCE_GIT_PROD_TOKEN" >> $GITHUB_ENV

      - name: Deploy
        run: |
          oc login --token=${{ secrets[env.secret_name_token] }} --server=$OC_SERVER
          make -C values/import-images/ install PROJECT=${{ matrix.project }}
